### ISSUE TITLE
Direct links to result are with anchors.

### ISSUE THREAD

**Issue by felixhayashi** [Tipue/Tipue-Search#21]
Hi,

thanks for making Tipue, it's a great feature for static sites.

I have a question:

Using Tipue in live mode: is it possible that Tipue uses an anchor near the area where it finds a result and uses this anchor in the results list url so it can be quickly navigated to?

Maybe Tipue could pass itself a parameter when submitting the form that points to the area where the match occured and then insert an anchor.

-Felix

**Comment by Tipue** [comment]
Thanks. I'm always looking for new ideas and I'll have a look into this for the next release.

**Comment by michael-milette** [comment]
Note: This has been partially addressed in Pull Request #39. Link URLs in the search results now include a "q" parameter.

This parameter can be parsed and used by a separate highlighter.js script to:

1. Create an anchor for each of the terms.
2. Highlight the search terms in the page.
3. Scroll down to the first matching search term.

In order to work, this script would need to be added to each of the pages included in the Tipue index. If the "q" parameter was not passed to the content page, the page would just display as it normally does without highlighting or scrolling.

I've started working on such a script but it isn't finished yet. Let me know if you are interested and I will post the code I've written so far.

Best regards,

Michael Milette
